### ISSUE TITLE
Incorrect number of constellations

### ISSUE THREAD

**Issue by sbanka** [astronexus/ATHYG-Database#2]
I looked in the table of constellations and there is 90 unique entries what is interesting as there is 88 constellations. There are two additional abbreviations: Eco, Sri.  Looks to me this is en error.

For each of these there exist one entry in ATHYG catalog:
1. Eco: id 1779605
2. Sir: id 1845743

For both entries cross reference like TYC, HD, HR look correct except Gaia DR3 designations:
1.  Eco: id 1779605 ---> Gaia DR3 4040825358109531600 entry doesn't exist in [cdsportal](http://cdsportal.u-strasbg.fr/?target=Gaia%20DR3%204040825358109531600%20)
2. Sir: id 1845743 ---> Gaia DR3 4096324302654797800 entry doesn't exist [cdsportal](http://cdsportal.u-strasbg.fr/?target=Gaia%20DR3%204096324302654797800)

**Comment by astronexus** [comment]
These were typos in a source file used to build v3.1. They have been corrected in v3.2 which is being released today.

- "Eco" -> Sco"
- "Sir" -> "Sgr"
